# Generated by Django 6.0.3 on 2026-03-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_p2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=20)),
                ('p2', models.CharField(max_length=20)),
                ('map_size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('h', 'H'), ('xh', 'XH'), ('g', 'G')], max_length=20)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='rounds.game')),
                ('p1_faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds_as_p1_hero', to='game.faction')),
                ('p1_hero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds_as_p1_hero', to='game.hero')),
                ('p2_faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds_as_p2_hero', to='game.faction')),
                ('p2_hero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds_as_p2_hero', to='game.hero')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
