# Generated by Django 6.0.3 on 2026-03-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='round',
            name='p2',
        ),
        migrations.AddField(
            model_name='round',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='round',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy (1)'), ('medium', 'Medium (2)'), ('hard', 'Hard (3)'), ('very hard', 'Very hard (4)'), ('heroic', 'Heroic (5)')], default='heroic', max_length=20),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='round',
            name='underground',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='round',
            name='water',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
