# Generated by Django 6.0.3 on 2026-03-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_remove_round_p1_remove_round_p2_round_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='water',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('islands', 'Islands')], default='no', max_length=20),
        ),
    ]
