# Generated by Django 6.0.3 on 2026-03-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0003_alter_round_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='map_size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
