# Generated by Django 6.0.3 on 2026-03-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0004_alter_round_map_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='map_size',
        ),
    ]
