# Generated by Django 6.0.3 on 2026-03-14 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_map'),
        ('rounds', '0005_remove_round_map_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='map_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.map'),
        ),
    ]
