# Generated by Django 6.0.3 on 2026-03-14 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_map'),
        ('rounds', '0006_round_map_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='p1_hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rounds_as_p1_hero', to='game.hero'),
        ),
        migrations.AlterField(
            model_name='round',
            name='p2_hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rounds_as_p2_hero', to='game.hero'),
        ),
    ]
