# Generated by Django 6.0.3 on 2026-03-14 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_map'),
        ('rounds', '0007_alter_round_p1_hero_alter_round_p2_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='p1_faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds_as_p1_faction', to='game.faction'),
        ),
        migrations.AlterField(
            model_name='round',
            name='p2_faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds_as_p2_faction', to='game.faction'),
        ),
    ]
