# Generated by Django 6.0.3 on 2026-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Heroes'},
        ),
        migrations.AddField(
            model_name='hero',
            name='profession',
            field=models.CharField(choices=[('knight', 'Knight'), ('cleric', 'Cleric'), ('ranger', 'Ranger'), ('druid', 'Druid'), ('alchemist', 'Alchemist'), ('wizard', 'Wizard'), ('demoniac', 'Demoniac'), ('heretic', 'Heretic'), ('death knight', 'Death Knight'), ('necromancer', 'Necromancer'), ('overlord', 'Overlord'), ('warlock', 'Warlock'), ('barbarian', 'Barbarian'), ('battle mage', 'Battle mage'), ('beastmaster', 'Beastmaster'), ('witch', 'Witch'), ('planeswalker', 'Planeswalker'), ('elementalist', 'Elementalist'), ('captain', 'Captain'), ('navigator', 'Navigator'), ('mercenary', 'Mercenary'), ('articer', 'Articer'), ('cheftain', 'Cheftain'), ('elder', 'Elder')], default='knight', max_length=20),
        ),
    ]
