# Generated by Django 6.0.3 on 2026-03-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_hero_options_hero_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='profession',
            new_name='hero_class',
        ),
    ]
