# Generated by Django 6.0.3 on 2026-03-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_profession_hero_hero_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='heroes/'),
        ),
    ]
