# Generated by Django 6.0.3 on 2026-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_hero_hero_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='factions/'),
        ),
    ]
