# Generated by Django 6.0.3 on 2026-03-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_faction_portrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='mapsize/')),
            ],
        ),
    ]
