# Generated by Django 6.0.3 on 2026-03-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='layout',
            field=models.ImageField(blank=True, null=True, upload_to='factions/'),
        ),
    ]
